project:
  type: website

website:
  title: "Flavien Loiseau"
  navbar:
    left:
      - publications.qmd
      - resources.qmd
        # right:
        #   - text: Google Scholar
        #     href: https://scholar.google.fr/citations?user=0UFftRMAAAAJ

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

