project:
  type: website
  resources: 
    - "resources/"

website:
  title: "Flavien Loiseau"
  description: Academic page of Flavien Loiseau.
    It contains information about my research (interests, publications, talks, etc.) and some open resources such as my PhD thesis template.
  site-url: https://floiseau.github.io/
  repo-url: https://github.com/floiseau/floiseau.github.io
  navbar:
    left:
      - publications.qmd
      - talks.qmd
      - resources.qmd
        # right:
        #   - text: Google Scholar
        #     href: https://scholar.google.fr/citations?user=0UFftRMAAAAJ

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    smooth-scroll: true
    mainfont: "Open Sans"
